Add validate ship position
smyshl/DI_Hackaton_01_Battleship pull request #4
Opened 2024-06-28 17:28 UTC by smyshl

Саша, я добавил проверку того, что корабль в границах поля и не касается других кораблей
Но что-то я торможу, поэтому долго и я вообще не потестировал как это работает.
Я потестирую
По хорошему надо сразу это делать, но может лучше, чтобы ты видел саму работу тоже
сегодня протестирую

2024-06-28 20:46 UTC, Alex-skigo99 requested changes

2024-06-28 20:46 UTC, Alex-skigo99 commented on classes.py
> +            for col in range(ship.hull[0][1], ship.hull[-1][1], 1):         # check another ships touching
Я немного не понял как работает твой вариант
Набросал свое видение:
.is_deck это флаг что в ячейке строится корабль. если мы поставим корабль(палубу) в ячейку сразу то он помешает проверке следующей палубы. Поэтому только в конце снимаем флаг .is_deck и ставим .ship_inside

    DTS = [(0,0),(-1,0),(-1,1),(0,1),(1,1),(1,0),(1,-1),(0,-1),(-1,-1)] # cells around ship
    def is_in_board(self, r, c) -> bool:
        '''check cell's coordinate.'''
        if r not in range(self.row) or c not in range(self.col):
            return False
        return True
    
      def fix_ship_in_board(self, is_fix:bool=True) -> None:
        '''if is_fix = True place ship in the board, else turn off .is_deck.'''
        for r in range(self.row):
            for c in range(self.col):
                if self.board[r][c].is_deck:
                    if is_fix:
                        self.board[r][c].ship_inside = True
                    self.board[r][c].is_deck = False
    
    def place_ship(self, ship: Ship) -> bool:
        '''Place a ship after check out it's position.'''
        for deck in ship.hull:
            r, c = deck
            for dt in Bd.DTS:
                dr, dc = dt
                if self.is_in_board(r+dr, c+dc):
                    if self.board[r+dr][c+dc].ship_inside:
                        self.fix_ship_in_board(False)
                        return False
            self.board[r][c].is_deck = True
        self.fix_ship_in_board()
        return True

2024-06-29 08:43 UTC, smyshl commented on classes.py
> +            for col in range(ship.hull[0][1], ship.hull[-1][1], 1):         # check another ships touching
Ты прав, у меня непонятно была написана логика и не работала
Когда я ее потестил и поправил, все стало ок, так что я этот реквест отзову и сделаю новый, думаю там все будет ясно

2024-06-29 08:44 UTC, smyshl commented
Не знаю какие комменты будут видны при закрытии реквеста, поэтому повторю здесь)
Ты прав, у меня непонятно была написана логика и не работала
Когда я ее потестил и поправил, все стало ок, так что я этот реквест отзову и сделаю новый, думаю там все будет ясно

2024-06-29 08:44 UTC, closed without merging